### ISSUE TITLE
Status of the game on other platforms

### ISSUE THREAD

**Issue by rammba** [Infiland/TheColorfulCreature#76]
The Colorful Creature is available on 4 platforms as far as I know:
- [Steam](https://store.steampowered.com/app/1651680/The_Colorful_Creature/)
- [Itch.io](https://infiland.itch.io/the-colorful-creature)
- [Game Jolt](https://gamejolt.com/games/TCC/369194)
- [Google App Store](https://play.google.com/store/apps/details?id=com.infiland.tcc)

However, only Steam is receiving constant updates.
What is the status of other platforms? Should other platforms also receive updates when new release is available here on GitHub?

**Comment by Infiland** [comment]
Steam stays as is as always. Gamejolt and Itch.io could possibly be removed or stay as is since keeping updates for them is difficult as I don't know if there is a way to automatize the process for updating, I think it's better having the steam version since it handles packages and autoupdates pretty well, there's no DLC content such as donation dlcs, soundtrack included so that also makes it difficult. As for Android, updates are currently postponed because I lost an android key for it so I can't update the game, but I will bring the android version back to normal.

**Comment by rammba** [comment]
Thanks for the explanation. I guess you can write some announcement/message on `itch.io` and `game jolt` that game won't receive updates there.
You can keep this issue or create new one for having Android app updated. I know there is also some approval on Google side after every update, but it shouldn't take long.

**Comment by Infiland** [comment]
Alright I updated the gamejolt and itch.io pages
